title: "Joel TERMONDJIAN"
description: "Data Analytics Engineer | 20 ans d’expérience en banque..."
theme: jekyll-theme-minimal
logo: "assets/Photo 1.jpg"
plugins:
  - jekyll-seo-tag
SEO_email: "joel.termondjian@hotmail.com"
show_downloads: false
github:
  is_project_page: false
